name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: ./build.sh
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/*.exe
            build/*.AppImage
            build/*.zip

  debug-build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: get version name
        id: get_version
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: build
        run: ./build.sh -d
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.get_version.outputs.SOURCE_TAG }}-debug
          draft: true
          files: |
            build/*.exe
            build/*.AppImage
            build/*.zip
